### PR TITLE
RightLink 10 patch

### PR DESCRIPTION
**Pull request by rshade**

### CODE REVIEW

**Comment by cdwilhelm** [comment]
change log?

**Comment by rshade** [comment]
Sorry man, forgot to say, it's not ready yet

**Comment by tusharshahrs** [comment]
There is php code instead of tomcat in updating dependencies, collectd, and connect scripts

**Comment by tusharshahrs** [comment]
Should the readme be updated to state that it also supports rl10.  Right now it just says v14

**Pull request merged**
